### ISSUE TITLE
Need any CI testing for your project?

### ISSUE THREAD

**Issue by TennisBowling** [ICSCodeClub/SkribbleHax#2]
We will integrate CI without editing any of your code, and make a PR to add.

Available anytime at @ICSCodeClub/ci-pros

**Comment by Pop101** [comment]
This isn't an issue just advertising

**Comment by TennisBowling** [comment]
this is funny
haaawaaaaaaaaaaaaaaaaa

**Comment by TennisBowling** [comment]
TOO HEATED

**Comment by Pop101** [comment]
lol
